vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end
vim.g.colors_name = "vividchalk"
vim.o.background = "dark"

local hi = vim.api.nvim_set_hl

-- Base palette
hi(0, "Normal", { fg = "#e8e8d3", bg = "#121212" })
hi(0, "NormalFloat", { fg = "#e8e8d3", bg = "#1c1c1c" })
hi(0, "Comment", { fg = "#5f5f5f", italic = true })
hi(0, "ColorColumn", { bg = "#1c1c1c" })
hi(0, "CursorLine", { bg = "#1c1c1c" })
hi(0, "CursorColumn", { bg = "#1c1c1c" })
hi(0, "LineNr", { fg = "#5f5f5f" })
hi(0, "CursorLineNr", { fg = "#fce94f", bold = true })
hi(0, "SignColumn", { bg = "#121212" })
hi(0, "VertSplit", { fg = "#3a3a3a", bg = "#121212" })
hi(0, "WinSeparator", { fg = "#3a3a3a", bg = "#121212" })
hi(0, "StatusLine", { fg = "#e8e8d3", bg = "#3a3a3a", bold = true })
hi(0, "StatusLineNC", { fg = "#5f5f5f", bg = "#1c1c1c" })
hi(0, "Pmenu", { fg = "#e8e8d3", bg = "#1c1c1c" })
hi(0, "PmenuSel", { fg = "#121212", bg = "#fce94f", bold = true })
hi(0, "PmenuSbar", { bg = "#3a3a3a" })
hi(0, "PmenuThumb", { bg = "#5f5f5f" })
hi(0, "Search", { fg = "#000000", bg = "#fce94f" })
hi(0, "IncSearch", { fg = "#000000", bg = "#e86820" })
hi(0, "Visual", { bg = "#262626" })
hi(0, "MatchParen", { fg = "#fce94f", bold = true })
hi(0, "NonText", { fg = "#3a3a3a" })
hi(0, "SpecialKey", { fg = "#3a3a3a" })
hi(0, "Folded", { fg = "#5f5f5f", bg = "#1c1c1c" })
hi(0, "FoldColumn", { fg = "#5f5f5f", bg = "#121212" })
hi(0, "WildMenu", { fg = "#121212", bg = "#fce94f" })
hi(0, "Title", { fg = "#fce94f", bold = true })
hi(0, "Directory", { fg = "#80a0ff" })
hi(0, "ErrorMsg", { fg = "#ffffff", bg = "#cc0000" })
hi(0, "WarningMsg", { fg = "#e86820" })
hi(0, "Question", { fg = "#99ad6a", bold = true })
hi(0, "ModeMsg", { bold = true })

-- Syntax
hi(0, "Constant", { fg = "#cf6a4c" })
hi(0, "String", { fg = "#99ad6a" })
hi(0, "Character", { fg = "#99ad6a" })
hi(0, "Number", { fg = "#cf6a4c" })
hi(0, "Boolean", { fg = "#cf6a4c" })
hi(0, "Float", { fg = "#cf6a4c" })

hi(0, "Identifier", { fg = "#c6b6ee" })
hi(0, "Function", { fg = "#fce94f" })

hi(0, "Statement", { fg = "#e86820", bold = true })
hi(0, "Conditional", { fg = "#e86820", bold = true })
hi(0, "Repeat", { fg = "#e86820", bold = true })
hi(0, "Label", { fg = "#e86820" })
hi(0, "Operator", { fg = "#e8e8d3" })
hi(0, "Keyword", { fg = "#e86820", bold = true })
hi(0, "Exception", { fg = "#e86820", bold = true })

hi(0, "PreProc", { fg = "#8fbfdc" })
hi(0, "Include", { fg = "#8fbfdc" })
hi(0, "Define", { fg = "#8fbfdc" })
hi(0, "Macro", { fg = "#8fbfdc" })
hi(0, "PreCondit", { fg = "#8fbfdc" })

hi(0, "Type", { fg = "#8fbfdc" })
hi(0, "StorageClass", { fg = "#8fbfdc", bold = true })
hi(0, "Structure", { fg = "#8fbfdc" })
hi(0, "Typedef", { fg = "#8fbfdc" })

hi(0, "Special", { fg = "#799d6a" })
hi(0, "SpecialChar", { fg = "#799d6a" })
hi(0, "Tag", { fg = "#fce94f" })
hi(0, "Delimiter", { fg = "#e8e8d3" })
hi(0, "SpecialComment", { fg = "#888888", italic = true })
hi(0, "Debug", { fg = "#cc0000" })

hi(0, "Underlined", { underline = true })
hi(0, "Ignore", { fg = "#3a3a3a" })
hi(0, "Error", { fg = "#ffffff", bg = "#cc0000", bold = true })
hi(0, "Todo", { fg = "#ffffff", bg = "#0000af", bold = true })

-- Diff
hi(0, "DiffAdd", { fg = "#99ad6a", bg = "#1c2b1c" })
hi(0, "DiffChange", { fg = "#8fbfdc", bg = "#1c1c2b" })
hi(0, "DiffDelete", { fg = "#cf6a4c", bg = "#2b1c1c" })
hi(0, "DiffText", { fg = "#ffffff", bg = "#2b2b1c", bold = true })

-- Treesitter
hi(0, "@variable", { fg = "#e8e8d3" })
hi(0, "@variable.builtin", { fg = "#cf6a4c" })
hi(0, "@string", { link = "String" })
hi(0, "@number", { link = "Number" })
hi(0, "@boolean", { link = "Boolean" })
hi(0, "@function", { link = "Function" })
hi(0, "@function.builtin", { fg = "#fce94f", italic = true })
hi(0, "@keyword", { link = "Keyword" })
hi(0, "@keyword.return", { fg = "#e86820", bold = true })
hi(0, "@type", { link = "Type" })
hi(0, "@type.builtin", { fg = "#8fbfdc", italic = true })
hi(0, "@comment", { link = "Comment" })
hi(0, "@operator", { link = "Operator" })
hi(0, "@punctuation", { fg = "#e8e8d3" })
hi(0, "@constant", { link = "Constant" })
hi(0, "@constant.builtin", { fg = "#cf6a4c", italic = true })
hi(0, "@property", { fg = "#c6b6ee" })
hi(0, "@field", { fg = "#c6b6ee" })
hi(0, "@parameter", { fg = "#e8e8d3", italic = true })
hi(0, "@tag", { fg = "#e86820" })
hi(0, "@tag.attribute", { fg = "#fce94f" })
hi(0, "@tag.delimiter", { fg = "#5f5f5f" })

-- LSP
hi(0, "DiagnosticError", { fg = "#cc0000" })
hi(0, "DiagnosticWarn", { fg = "#e86820" })
hi(0, "DiagnosticInfo", { fg = "#8fbfdc" })
hi(0, "DiagnosticHint", { fg = "#5f5f5f" })
hi(0, "DiagnosticUnderlineError", { undercurl = true, sp = "#cc0000" })
hi(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = "#e86820" })
hi(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = "#8fbfdc" })
hi(0, "DiagnosticUnderlineHint", { undercurl = true, sp = "#5f5f5f" })
